version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "This will fail intentionally"
      - exit 1
artifacts:
  files:
    - '**/*'
